version: '3.8'
services:
  mydb:
    container_name: mydb
    image: mysql:8
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_PASS
      - MYSQL_DATABASE=$MYSQLDB
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_LOCAL_PORT 
    volumes:
      - ./src/db/db.init.sql:/docker-entrypoint-initdb.d/db.sql