version: '3.8'
services:
  mysql-db:
    image: mysql:8
    restart: always
    env_file: ./.env
    environment:
      - MYSQL_PASSWORD=$MYSQLDB_PASS
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_PASS
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
volumes:
  mysql: